!define primaryColor   #4267b2
!define secondaryColor #56bd77
skinparam handwritten true
skinparam shadowing false

skinparam Default {
  FontName inconsolata
}
skinparam Participant {
    FontColor black
    BackgroundColor #ffffff
    BorderColor black
}
skinparam Arrow {
  Color primaryColor
  FontColor primaryColor
}
skinparam Activity {
  FontColor secondaryColor
  StartColor primaryColor
  EndColor primaryColor
  BackgroundColor #ffffff
  BorderColor secondaryColor
  DiamondBackgroundColor #ffffff
  DiamondBorderColor secondaryColor
  DiamondFontColor secondaryColor
}
skinparam Sequence {
  LifeLineBorderColor black
}
